name: multiarch-pm2

on: [push]

jobs:
  pm2-build:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm, arm64]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: login to docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: building pm2 
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          docker buildx build --platform ${{ matrix.arch }} -t rjpadilla/pm2:${{ matrix.arch }} .
          docker push rjpadilla/pm2:${{ matrix.arch }}
  pm2-manifest:
    needs: pm2-build
    runs-on: ubuntu-20.04
    steps:
      - name: login to docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: deploying to docker
        run: |
          docker manifest create rjpadilla/pm2:latest rjpadilla/pm2:amd64 rjpadilla/pm2:arm rjpadilla/pm2:arm64
          docker manifest inspect rjpadilla/pm2:latest
          docker manifest annotate --arch amd64 rjpadilla/pm2:latest rjpadilla/pm2:amd64
          docker manifest annotate --arch arm rjpadilla/pm2:latest rjpadilla/pm2:arm
          docker manifest annotate --arch arm64 rjpadilla/pm2:latest rjpadilla/pm2:arm64
          docker manifest inspect rjpadilla/pm2:latest
          docker manifest push rjpadilla/pm2:latest
