name: multiarch

on: push

jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v2
      # - name: Login to Docker 
      #   run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: build and deploy docker image
        run: |
          docker buildx ls
