name: multiarch

on: push

jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v2
      - name: Login to Docker 
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: build and deploy docker image
        run: |
          docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          docker buildx ls
          docker buildx build --platform linux/arm/v7 -t rjpadilla/arch-test:armv7 .
          docker push rjpadilla/arch-test:armv7
          # docker run --rm arm-build
