name: multiarch

on: push

jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v2
      - name: Login to Docker hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERAPIKEY }}
      - name: Build and deploy docker image
        run: |
          docker buildx ls
